services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    environment:
      - DB_HOST=db
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://backend:${API_PORT}
        VITE_API_VERSION: v1
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/app
    environment:
      - VITE_API_URL=http://backend:${API_PORT}
      - VITE_API_VERSION=v1
    depends_on:
      - backend

  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
